
#ifndef GAME_LIN_ACCEL_H
#define GAME_LIN_ACCEL_H


#include "SGUI.h"

#define GAME_LIN_ACCEL_BUTTONS 1

#define GAME_LIN_ACCEL_B_POWER_P 2
#define GAME_LIN_ACCEL_B_POWER_X0 520
#define GAME_LIN_ACCEL_B_POWER_Y0 190
#define GAME_LIN_ACCEL_B_POWER_X1 GAME_LIN_ACCEL_B_POWER_X0+250 
#define GAME_LIN_ACCEL_B_POWER_Y1 GAME_LIN_ACCEL_B_POWER_Y0+100
#define GAME_LIN_ACCEL_B_POWER_RX 10
#define GAME_LIN_ACCEL_B_POWER_RY 10
#define GAME_LIN_ACCEL_B_POWER_FW 2
#define GAME_LIN_ACCEL_B_POWER_BC 0xFFFF
#define GAME_LIN_ACCEL_B_POWER_FC 0x21E2
#define GAME_LIN_ACCEL_B_POWER_T 0
#define GAME_LIN_ACCEL_B_POWER_TC 0
#define GAME_LIN_ACCEL_B_POWER_TMX 0
#define GAME_LIN_ACCEL_B_POWER_TMY 0
#define GAME_LIN_ACCEL_B_POWER_STATE 0
#define GAME_LIN_ACCEL_B_POWER_DELAY 500
#define GAME_LIN_ACCEL_B_POWER_ACT btn_linAccelPower


void game_LinAccel_init(void);


#endif
