
#ifndef GAME_CIRC_ACCEL_H
#define GAME_CIRC_ACCEL_H


#include "SGUI.h"


#define GAME_CIRC_ACCEL_POWER_OFF_COLOR 0xAD55
#define GAME_CIRC_ACCEL_POWER_ON_COLOR 0x6DCA


#define GAME_CIRC_ACCEL_B_POWER_P 3
#define GAME_CIRC_ACCEL_B_POWER_X0 560
#define GAME_CIRC_ACCEL_B_POWER_Y0 320
#define GAME_CIRC_ACCEL_B_POWER_X1 GAME_CIRC_ACCEL_B_POWER_X0+150
#define GAME_CIRC_ACCEL_B_POWER_Y1 GAME_CIRC_ACCEL_B_POWER_Y0+100
#define GAME_CIRC_ACCEL_B_POWER_RX 10
#define GAME_CIRC_ACCEL_B_POWER_RY 10
#define GAME_CIRC_ACCEL_B_POWER_FW 2
#define GAME_CIRC_ACCEL_B_POWER_BC GAME_CIRC_ACCEL_POWER_OFF_COLOR
#define GAME_CIRC_ACCEL_B_POWER_FC 0x0000
#define GAME_CIRC_ACCEL_B_POWER_T 0
#define GAME_CIRC_ACCEL_B_POWER_TC 0
#define GAME_CIRC_ACCEL_B_POWER_TMX 0
#define GAME_CIRC_ACCEL_B_POWER_TMY 0
#define GAME_CIRC_ACCEL_B_POWER_STATE 1
#define GAME_CIRC_ACCEL_B_POWER_DELAY 500
#define GAME_CIRC_ACCEL_B_POWER_ACT btn_circAccelPower

#define GAME_CIRC_ACCEL_B_CLEAR_P 3
#define GAME_CIRC_ACCEL_B_CLEAR_X0 869
#define GAME_CIRC_ACCEL_B_CLEAR_Y0 150
#define GAME_CIRC_ACCEL_B_CLEAR_X1 GAME_CIRC_ACCEL_B_CLEAR_X0+120
#define GAME_CIRC_ACCEL_B_CLEAR_Y1 GAME_CIRC_ACCEL_B_CLEAR_Y0+70
#define GAME_CIRC_ACCEL_B_CLEAR_RX 10
#define GAME_CIRC_ACCEL_B_CLEAR_RY 10
#define GAME_CIRC_ACCEL_B_CLEAR_FW 2
#define GAME_CIRC_ACCEL_B_CLEAR_BC 0xFFFF
#define GAME_CIRC_ACCEL_B_CLEAR_FC 0x3823
#define GAME_CIRC_ACCEL_B_CLEAR_T 0
#define GAME_CIRC_ACCEL_B_CLEAR_TC 0
#define GAME_CIRC_ACCEL_B_CLEAR_TMX 0
#define GAME_CIRC_ACCEL_B_CLEAR_TMY 0
#define GAME_CIRC_ACCEL_B_CLEAR_STATE 1
#define GAME_CIRC_ACCEL_B_CLEAR_DELAY 500
#define GAME_CIRC_ACCEL_B_CLEAR_ACT btn_clear


enum gameCircAccelLevel
{
  PORTAL_1 = 1,
  PORTAL_2,
  PORTAL_3,
  PORTAL_4,
  PORTAL_5
};


void game_circAccel_init(void);
void game_circAccel_handler(void);


#endif
